name: CI Script

on:
  pull_request:
    branches: [ "master" ]
permissions: write-all

jobs:
  ClangFormat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Running clang-format
        run: clang-format -i $(find -type f -a \( -name "*.c" -o -name "*.h" \))
      - name: Checking for non-conforming files
        run: git diff --exit-code -- ':!*.yml'

  Build:
    needs: [ClangFormat]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing Packages
      run: sudo apt-get update && sudo apt-get install -y libcriterion-dev autotools-dev autoconf
    - name: Running autoreconf
      run: autoreconf --install --verbose --force
    - name: Running configure
      run: ./configure
    - name: Running basic make
      run: make

  TestSuites:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing Packages
      run: sudo apt-get update && sudo apt-get install -y libcriterion-dev autotools-dev autoconf
    - name: Running autoreconf
      run: autoreconf --install --verbose --force
    - name: Running configure
      run: ./configure
    - name: Running make check
      run: make check
